spring:
  flyway:
    baseline-on-migrate: true
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: never
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: postgres
    password: somepassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate

server:
  port: 8081
