version: "3.7"

services:
  postgres:
    image: postgres
    container_name: postgres
    volumes:
      - "~/project:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: somepassword
  api:
    build:
      context: .
    container_name: api
    ports:
      - "8081:8081"
  telegram-bot:
    build:
      context: ./telegram-bot
    container_name: telegram-bot
    environment:
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
